#!/bin/bash

# clone fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2
VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

source ${ONE_LOCAL_VAR}/remotes/datastore/libfs.sh
logger "${ONE_LOCAL_VAR}/remotes/datastore/libfs.sh"

SRC_PATH=`arg_path $SRC`
DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`
BASE_PATH=`dirname $SRC_PATH`
DST_DIR=`generate_image_path`
DST_BASE=`dirname $DST_PATH`

logger "SRC=$SRC"
logger "SRC_PATH=$SRC_PATH"
logger "DST=$DST"
logger "DST_PATH=$DST_PATH"
logger "BASE_PATH=$BASE_PATH"
logger "DST_DIR=$DST_DIR"
logger "DST_BASE=$DST_BASE"

ssh_make_path $DST_HOST $DST_DIR

tool="${ONE_LOCAL_VAR}/remotes/hooks/vdc/tool.py"
conf="${ONE_LOCAL_VAR}/remotes/hooks/vdc/mkconfig.py"
vdc="/home/gareth/Git/vdc/vdc-client"
vdctool="$vdc/vdc-tool"
vdcstore="$vdc/vdc-store"

NAME="ON_IM_$VMID"
CACHE_SIZE="none"
CACHE_LVM="none"
DS_NAME="none"

case $SRC in
http://*)
    log "Downloading $SRC"
    RMT_CMD="$WGET -O $DST_DIR $SRC"
    ssh_exec_and_log "$DST_HOST" "$RMT_CMD" "Error downloading $SRC"
    ;;

*)
    log "Cloning $SRC in $DST_DIR"
    logger "${DST_HOST}" "cp -r $SRC_PATH/* $DST_DIR" 
    ssh_exec_and_log "${DST_HOST}" "cp -r $SRC_PATH/* $DST_DIR" "Error copying $SRC to $DST_DIR"
    ;;
esac

eval `${tool} ln $VMID $DSID`
${tool} add ${NAME} ${DST_DIR} 0
${conf}
sleep 2

function execute {
	logger "@$DST_HOST ${1}" 
	ssh_exec_and_log ${DST_HOST} "${1}" "${2}"
}

execute "sudo $vdctool -n $NAME --create -c${CACHE_SIZE} --nouuid lvm:${CACHE_LVM}/${NAME} vdc:${DS_NAME}/${NAME}" "Error creating Cache"
execute "sudo $vdcstore -n ${NAME}" "Error starting VDC"
execute "mkdir ${DST_BASE}; ln -s /dev/vdc/mapper/${NAME} ${DST_PATH}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${NAME}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${NAME}"

exit 0
