#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
ROOT=$(dirname $(dirname $(dirname $0)))
source ${ROOT}/hooks/vdc/common.sh

SRC=$1
DST=$2
VMID=$3
DSID=$4

tool="${ROOT}/hooks/vdc/tool.py"
conf="${ROOT}/hooks/vdc/mkconfig.py"
gids="${ROOT}/hooks/vdc/get_image_ids.py"
vdc="${ROOT}/../vdc-nebula/remotes/binaries"
vdctool="$vdc/vdc-tool"
vdcstore="$vdc/vdc-store"

#NAME="ON_IM_$VMID"

eval `${gids} $VMID`

vdc_log "Set NAME to $NAME for $VMID"
vdc_log `${gids} $VMID`

CACHE_SIZE="none"
CACHE_LVM="none"
DS_NAME="none"

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`
SRC_ARG_PATH=`arg_path $SRC`

DST_DS_PATH="$(dirname $(dirname $(dirname $DST_PATH)))"
SRC_DS_PATH="$(dirname $(dirname $SRC_ARG_PATH))"
SRC_PATH="${DST_DS_PATH}${SRC_ARG_PATH##$SRC_DS_PATH}"

vdc_log "Make Path ($DST_HOST) ($DST_DIR)"
ssh_make_path $DST_HOST $DST_DIR

vdc_log "${tool} ln $VMID $DSID $DST_HOST"
vdc_log "[`${tool} ln $VMID $DSID $DST_HOST`]"
eval `${tool} ln $VMID $DSID $DST_HOST`

execute ${DS_NAME} ${conf} "Error Updating VDC Server Config"
sleep 2
execute $DST_HOST "sudo $vdctool -n  ${NAME} --create -c${CACHE_SIZE} --nouuid lvm:${CACHE_LVM}/${NAME} vdc:${DS_NAME}/${NAME}" "Error creating Cache"
execute $DST_HOST "sudo $vdcstore -n ${NAME}" "Error starting VDC"
execute $DST_HOST "sudo $vdctool  -n ${NAME} --wait STARTED" "Failed waiting on vdc-start"
execute $DST_HOST "cd ${DST_DIR}; rm -f ${DST_PATH}; ln -s /dev/vdc/mapper/${NAME} ${DST_PATH}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${NAME}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${NAME}"

exit 0
