#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
ROOT=$(dirname $(dirname $(dirname $0)))
source ${ROOT}/hooks/vdc/common.sh

SRC=$1
DST=$2
VMID=$3
DSID=$4

tool="${ROOT}/hooks/vdc/tool.py"
conf="${ROOT}/hooks/vdc/mkconfig.py"
gids="${ROOT}/hooks/vdc/get_image_ids.py"
vdc="${ROOT}/../vdc-nebula/remotes/binaries"
vdctool="$vdc/vdc-tool"
vdcstore="$vdc/vdc-store"

eval `${gids} $VMID`

#NAME="ON_IM_$VMID"
CACHE_SIZE="none"
CACHE_LVM="none"
DS_NAME="none"
DST_HOST=`arg_host $SRC`

vdc_log "${tool} ln $VMID $DSID $DST_HOST"
eval `${tool} ln $VMID $DSID $DST_HOST`

CACHE_PATH="/dev/${CACHE_LVM}"
execute $DST_HOST "sudo $vdctool -n $NAME --stop" "Error stopping Cache"
execute $DST_HOST "${vdctool} --wait STOPPED" "Failed waiting on vdc-stop"
execute $DST_HOST "sudo lvremove -f ${CACHE_PATH}/${NAME}" "Error removing Cache LVM"
exit 0
