#!/bin/bash

SRC_HOST=$1
DST_HOST=$2
DIR_HOST=$3
VMID=$4
DSID=$5
TEMP=$6

logger "POSTMIGRATE :: ${VMID}"

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

tool="${ONE_LOCAL_VAR}/remotes/hooks/vdc/tool.py"
conf="${ONE_LOCAL_VAR}/remotes/hooks/vdc/mkconfig.py"
vdc="/home/gareth/Git/vdc/vdc-client"
NAME="ON_IM_$VMID"
vdctool="sudo $vdc/vdc-tool -n ${NAME}"
vdcstore="sudo $vdc/vdc-store -n ${NAME}"

log "Running Migrate"
ssh_exec_and_log ${SRC_HOST} "${vdctool} --stop"
sleep 2
CACHE_PATH="/dev/${CACHE_LVM}"
ssh_exec_and_log ${SRC_HOST}  "sudo lvremove -f ${CACHE_PATH}/${NAME}" "Error removing Cache LVM"

exit 0
