#!/bin/bash

#
#	Process:
#		Start vdc-store on $DST
#		Set $DST to read-write
#		Run tool --migrate on $SRC
#

SRC_HOST=$1
DST_HOST=$2
DIR_HOST=$3
VMID=$4
DSID=$5
TEMP=$6

logger "PREMIGRATE :: ${VMID}"

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

source $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $(dirname $(dirname $0)))
source ${DRIVER_PATH}/datastor/libfs.sh
XPATH="${DRIVER_PATH}/datastore/xpath.rb -b $TEMP"
unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH  	/VM/TEMPLATE/DISK/DATASTORE_ID)

DSID="${XPATH_ELEMENTS[0]}"

tool="${DRIVER_PATH}/hooks/vdc/tool.py"
conf="${DRIVER_PATH}/hooks/vdc/mkconfig.py"
vdc="/home/gareth/Git/vdc/vdc-client"
NAME="ON_IM_$VMID"
vdctool="sudo $vdc/vdc-tool -n ${NAME}"
vdcstore="sudo $vdc/vdc-store -n ${NAME}"

CACHE_SIZE="none"
CACHE_LVM="none"
DS_NAME="none"

logger "==> ${tool} ln $VMID $DSID $DST_HOST"
logger "[[ `${tool} ln $VMID $DSID $DST_HOST` ]]"
eval `${tool} ln $VMID $DSID $DST_HOST`

function execute {
	logger "* exec @$1 $2"
	ssh_exec_and_log $1 $2 $3
}

execute ${DST_HOST} "$vdctool --create -c${CACHE_SIZE} --nouuid lvm:${CACHE_LVM}/${NAME} vdc:${DS_NAME}/${NAME}" "Error creating Cache"
execute ${DST_HOST} "${vdcstore} -R" "Unable to start cache on $DST_HOST"
execute ${SRC_HOST} "${vdctool} --wait STARTED" "Failed waiting on vdc-start"
execute ${DST_HOST} "${vdctool} --readwrite" "Unable to set RW mode"
execute ${SRC_HOST} "${vdctool} --migrate ${DST_HOST}" "Unable to complete cache migrate"
execute ${SRC_HOST} "${vdctool} --wait MIGRATE" "Failed waiting on vdc-migrate"

#ssh_exec_and_log ${DST_HOST} "$vdctool --create -c${CACHE_SIZE} --nouuid lvm:${CACHE_LVM}/${NAME} vdc:${DS_NAME}/${NAME}" "Error creating Cache"
#logger "* exec @${DST_HOST} ${vdcstore} -R"
#ssh_exec_and_log ${DST_HOST} "${vdcstore} -R" "Unable to start cache on $DST_HOST"
#logger "* exec @${SRC_HOST} "${vdctool} --wait STARTED"
#ssh_exec_and_log ${SRC_HOST} "${vdctool} --wait STARTED" "Failed waiting on vdc-start"

#logger "* exec @${DST_HOST} ${vdctool} --readwrite"
#ssh_exec_and_log ${DST_HOST} "${vdctool} --readwrite" "Unable to set RW mode"

#logger "* exec @${SRC_HOST} ${vdctool} --migrate ${DST_HOST}"
#ssh_exec_and_log ${SRC_HOST} "${vdctool} --migrate ${DST_HOST}" "Unable to complete cache migrate"
#logger "* exec @${SRC_HOST} "${vdctool} --wait MIGRATE"
#ssh_exec_and_log ${SRC_HOST} "${vdctool} --wait MIGRATE" "Failed waiting on vdc-migrate"

exit 0
