#!/bin/sh

#
#	Process:
#		Start vdc-store on $DST
#		Set $DST to read-write
#		Run tool --migrate on $SRC
#

SRC_HOST=$1
DST_HOST=$2
DIR_HOST=$3
VMID=$4
DSID=$5
TEMP=$6

logger "PREMIGRATE :: ${VMID}"

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

tool="${ONE_LOCAL_VAR}/remotes/hooks/vdc/tool.py"
conf="${ONE_LOCAL_VAR}/remotes/hooks/vdc/mkconfig.py"
vdc="/home/gareth/Git/vdc/vdc-client"
NAME="ON_IM_$VMID"
vdctool="sudo $vdc/vdc-tool -n ${NAME}"
vdcstore="sudo $vdc/vdc-store -n ${NAME}"

CACHE_SIZE="none"
CACHE_LVM="none"
DS_NAME="none"

logger "==> ${tool} ln $VMID $DSID $DST_HOST"
logger "[[ `${tool} ln $VMID $DSID $DST_HOST` ]]"
eval `${tool} ln $VMID $DSID $DST_HOST`

ssh_exec_and_log ${DST_HOST} "$vdctool --create -c${CACHE_SIZE} --nouuid lvm:${CACHE_LVM}/${NAME} vdc:${DS_NAME}/${NAME}" "Error creating Cache"
log "Starting target store on ${DST_HOST}"
ssh_exec_and_log ${DST_HOST} "${vdcstore} -R" "Unable to start cache on $DST_HOST"
sleep 2
log "Setting target RW"
ssh_exec_and_log ${DST_HOST} "${vdctool} --readwrite"
sleep 2
log "Running Migrate"
ssh_exec_and_log ${SRC_HOST} "${vdctool} --migrate ${DST_HOST}"

exit 0
