#!/bin/bash

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH\
 					/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/HOST)

BASE_PATH="${XPATH_ELEMENTS[0]}"
SRC="${XPATH_ELEMENTS[1]}"
DST_HOST="${XPATH_ELEMENTS[2]:-$HOST}"

mkdir -p "$BASE_PATH"
set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS"

DST=`generate_image_path`

log "Copying $SRC to $DST on $DST_HOST"
logger "Copying $SRC to $DST on $DST_HOST"

logger "cp -rf $SRC $DST" 
ssh_exec_and_log "$DST_HOST" "sudo chown -R oneadmin:cloud $SRC"
ssh_exec_and_log "$DST_HOST" "cp -rf $SRC $DST" "Error copying $SRC to $DST"

echo "$DST"
