#!/bin/bash

DRV_ACTION=$1
ID=$2

logger "DS MONITOR :: ($ID)"

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh
DRIVER_PATH=$(dirname $(dirname $0))
source ${DRIVER_PATH}/libfs.sh
XPATH="${DRIVER_PATH}/xpath.rb -b $DRV_ACTION"
unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/HOST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/VG_NAME)

HOST="${XPATH_ELEMENTS[0]}"
VG_NAME="${XPATH_ELEMENTS[1]}"

MONITOR_SCRIPT=$(cat <<EOF
VG_OPTS="--units M -C --noheadings --nosuffix $VG_NAME"
TOTAL_MB=\$(sudo vgdisplay -o vg_size \$VG_OPTS|tr -d " ")
FREE_MB=\$(sudo vgdisplay -o vg_free \$VG_OPTS|tr -d " " )
USED_MB=\$(awk "BEGIN { print \$TOTAL_MB - \$FREE_MB } ")

echo "TOTAL_MB=\$TOTAL_MB"
echo "FREE_MB=\$FREE_MB"
echo "USED_MB=\$USED_MB"
logger "Free Space (\$TOTAL_MB)"
EOF
)

MONITOR_DATA=$(ssh_monitor_and_log $HOST "$MONITOR_SCRIPT" 2>&1)
MONITOR_STATUS=$?

if [ "$MONITOR_STATUS" = "0" ]; then
    echo "$MONITOR_DATA" | tr ' ' '\n'
else
    echo "$MONITOR_DATA"
    exit $MONITOR_STATUS
fi

exit 0
