#!/bin/bash

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH\
 					/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/HOST)

SRC="${XPATH_ELEMENTS[0]}"
BASE_PATH="${XPATH_ELEMENTS[1]}"
DST_HOST="${XPATH_ELEMENTS[2]:-$HOST}"

BASENAME_SRC=`basename "${SRC##$BASE_PATH}"`

if [ -f "$SRC/Image.img" -a `dirname "$SRC"` = "$BASE_PATH" -a -n "$BASENAME_SRC" ]
then
    log "Removing $SRC from the image repository"
    logger "Removing $SRC from the image repository"
    ssh_exec_and_log "$DST_HOST" "rm -rf $SRC" "Error deleting $SRC"
else
	logger "Error: $SRC"
    log_error "Bad formed or unavailable Image source: ${SRC}"
    exit 1
fi

