#!/bin/bash

DRV_ACTION=$1
ID=$2

logger "DS STAT :: ($ID)"

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh
DRIVER_PATH=$(dirname $(dirname $0))
source ${DRIVER_PATH}/libfs.sh
XPATH="${DRIVER_PATH}/xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH /DS_DRIVER_ACTION_DATA/IMAGE/PATH)
SRC="${XPATH_ELEMENTS[0]}"
logger "SRC=$SRC"
siz=`blockdev --getsz $SRC`
logger "SIZE=$siz"
expr $siz \/ 2 \/ 1024
exit 0

